@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTMwMDU2ODJ9.kIoDSsonfADSCcGiRrOBovNI0wAW802JsMC9kBp9iqc

### Products index
GET http://localhost:3000/products.json



### Products create

POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
"name": "greenpapaya", 
"price": "4", 
"image_url": "www.papaya.com", 
"description": "red, small, round",
"supplier_id": 1
}

### Products show

GET http://localhost:3000/products/1.json
Content-Type: application/json



### Product update
PATCH http://localhost:3000/products/5.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "yellow watermelon",
  "price": -3
}

### Delete product
DELETE http://localhost:3000/products/9.json
Authorization: Bearer {{jwt}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "melissa",
  "email": "melissa@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Orders create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{

  "product_id": 3,
  "quantity": 2,
  "subtotal": 6,
  "tax": 1.20,
  "total": 7.20
  
  }

### Orders show


GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}


### Orders index


GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### Carted_Products create
POST http://localhost:3000/carted_products.json 
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 1,
  "product_id": 1,
  "quantity": 1,
  "status": "carted",
  "order_id": 1
}

### CARTED PRODUCTS INDEX
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}

### CARTED PRODUCTS DESTROY
DELETE http://localhost:3000/carted_products/5.json
Authorization: Bearer {{jwt}}

