### Products index
GET http://localhost:3000/products.json

### Products create

POST http://localhost:3000/products.json
Content-Type: application/json

{
"name": "eggplant", 
"price": "4", 
"image_url": "www.papaya.com", 
"description": "red, small, round"
}

### Products show

GET http://localhost:3000/products/1.json

### Product update
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "name": "yellow watermelon",
  "price": -3
}

### Delete product

DELETE http://localhost:3000/products/2.json